name: 🛠️ Suggestion / Feature Request
description: File a feature request or suggestion for a new feature
title: '[feat]: '
labels: ['enhancement']
body:
  - type: checkboxes
    attributes:
      label: Package
      description: Select the package(s) this feature request applies to.
      options:
        - label: jhx
        - label: @jhxdev/elysia
        - label: @jhxdev/express
        - label: @jhxdev/fastify
        - label: @jhxdev/hono
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the feature
      description: Please describe the feature as clear and concise as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution / Benefits
      description: Describe the solution and/or benefits of the feature. Include any code snippets or examples.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Other details related to the feature.