import type {
    ServerJhx,
    ServerJhxComponentProps,
    ServerJhxComponentType,
    ServerJhxHandler,
    ServerJhxPartialRoute,
    ServerJhxProps,
    ServerJhxRoute,
} from '../types';

export const createJhxComponent = <
    TDom extends object,
    TReturn,
    TReq,
    TRes,
    THandler extends ServerJhxHandler<TReturn, TReq, TRes>,
    TBaseProps extends ServerJhxProps<TDom, TReturn, TReq, TRes, THandler>,
    TCompProps extends ServerJhxComponentProps<TDom, TReturn, TReq, TRes, THandler, TBaseProps>,
    TRoute extends ServerJhxRoute<TReturn, TReq, TRes, THandler>,
    TPartialRoute extends ServerJhxPartialRoute<TReturn, TReq, TRes, THandler>,
>(
    jhx: ServerJhx<TDom, TReturn, TReq, TRes, any, THandler, TRoute, TPartialRoute>,
) => {
    const JhxComponent: ServerJhxComponentType<
        TDom,
        TReturn,
        TReq,
        TRes,
        THandler,
        TBaseProps,
        TCompProps
    > = (props) => {
        const {
            boost,
            confirm,
            disable,
            disabledElt,
            disinherit,
            encoding,
            ext,
            headers,
            history,
            historyElt,
            include,
            indicator,
            inherit,
            method,
            params,
            preserve,
            prompt,
            pushUrl,
            replaceUrl,
            request,
            route,
            select,
            selectOob,
            swap,
            swapOob,
            sync,
            target,
            trigger,
            validate,
            vals,
            vars,
            onAbort,
            onAfterOnLoad,
            onAfterProcessNode,
            onAfterRequest,
            onAfterSettle,
            onAfterSwap,
            onBeforeCleanupElement,
            onBeforeHistorySave,
            onBeforeOnLoad,
            onBeforeProcessNode,
            onBeforeRequest,
            onBeforeSend,
            onBeforeSwap,
            onBeforeTransition,
            onConfigRequest,
            onConfirm,
            onHistoryCacheError,
            onHistoryCacheHit,
            onHistoryCacheMiss,
            onHistoryCacheMissLoad,
            onHistoryCacheMissLoadError,
            onHistoryRestore,
            onLoad,
            onNoSSESourceError,
            onOnLoadError,
            onOobAfterSwap,
            onOobBeforeSwap,
            onOobErrorNoTarget,
            onPrompt,
            onPushedIntoHistory,
            onReplacedInHistory,
            onResponseError,
            onSendAbort,
            onSendError,
            onSseError,
            onSseOpen,
            onSwapError,
            onTargetError,
            onTimeout,
            onValidateUrl,
            onValidationFailed,
            onValidationHalted,
            onValidationValidate,
            onXhrAbort,
            onXhrLoadend,
            onXhrLoadstart,
            onXhrProgress,
            jhxConfig,
            as: Tag = 'div',
            children,
            ...remainingProps
        } = props;

        const attrs = jhx(
            {
                boost,
                confirm,
                disable,
                disabledElt,
                disinherit,
                encoding,
                ext,
                headers,
                history,
                historyElt,
                include,
                indicator,
                inherit,
                method,
                params,
                preserve,
                prompt,
                pushUrl,
                replaceUrl,
                request,
                route,
                select,
                selectOob,
                swap,
                swapOob,
                sync,
                target,
                trigger,
                validate,
                vals,
                vars,
                onAbort,
                onAfterOnLoad,
                onAfterProcessNode,
                onAfterRequest,
                onAfterSettle,
                onAfterSwap,
                onBeforeCleanupElement,
                onBeforeHistorySave,
                onBeforeOnLoad,
                onBeforeProcessNode,
                onBeforeRequest,
                onBeforeSend,
                onBeforeSwap,
                onBeforeTransition,
                onConfigRequest,
                onConfirm,
                onHistoryCacheError,
                onHistoryCacheHit,
                onHistoryCacheMiss,
                onHistoryCacheMissLoad,
                onHistoryCacheMissLoadError,
                onHistoryRestore,
                onLoad,
                onNoSSESourceError,
                onOnLoadError,
                onOobAfterSwap,
                onOobBeforeSwap,
                onOobErrorNoTarget,
                onPrompt,
                onPushedIntoHistory,
                onReplacedInHistory,
                onResponseError,
                onSendAbort,
                onSendError,
                onSseError,
                onSseOpen,
                onSwapError,
                onTargetError,
                onTimeout,
                onValidateUrl,
                onValidationFailed,
                onValidationHalted,
                onValidationValidate,
                onXhrAbort,
                onXhrLoadend,
                onXhrLoadstart,
                onXhrProgress,
            },
            {
                ...jhxConfig,
                stringify: false,
            },
        );

        return (
            <Tag
                {...attrs}
                {...remainingProps}
            >
                {children}
            </Tag>
        );
    };

    JhxComponent.displayName = 'JhxComponentFactory';
    return JhxComponent;
};
